[project]
name = "indekkusu"
version = "0.1.0"
description = "index and search doujinshi"
authors = [{ name = "Aloxaf", email = "aloxafx@gmail.com" }]
dependencies = [
    "click>=8.1.7",
    "opencv-python>=4.9.0.80",
    "pillow>=10.3.0",
    "tqdm>=4.66.4",
    "usearch>=2.12.0",
    "plyvel>=1.5.1",
    "loguru>=0.7.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "Apache-2.0" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
